//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer
    {
        public int id { get; set; }
        public string Name { get; set; }
        public short Length { get; set; }
        public short Weight { get; set; }
        public short Classid { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
